name: CD

on:
  push:
    branches:
      - dev

jobs:
  publish-beta:
    uses: ./.github/workflows/publish.yml
    with:
      branch: dev

  approval:
    needs: publish-beta
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "Approved"

  promote-to-main:
    needs: approval
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin dev
          git merge origin/dev -X theirs --no-edit
          git push origin main

  publish-stable:
    needs: promote-to-main
    uses: ./.github/workflows/publish.yml
    with:
      branch: main
