name: Publish

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Publishing from ${{ inputs.branch }}"
